Redux update
evomimic/map-proto1 pull request #39
Opened 2023-04-17 22:55 UTC by nphias

2023-04-17 23:44 UTC, evomimic requested changes
Overall looks good. Curious about the rationale behind the changes to dna.yaml and happ.yaml
(e.g., renaming of map-proto1 to map-descriptors seems to significantly narrow the scope).

I've been thinking a lot about packaging lately also and think we need to make some changes. But, unless these changes are somehow critical to the UI framework change, I'd suggest holding off on changing the dna/happ definitions in this PR.

2023-04-20 11:56 UTC, nphias commented
rejected

2023-04-20 11:57 UTC, nphias commented
re-opened with changes

2023-04-20 15:38 UTC, evomimic approved these changes

2023-04-20 15:38 UTC, merged